[package]
name = "bstruct_browser_base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at 
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
serde-wasm-bindgen = "0"
js-sys = "0.3"

[dependencies.web-sys]
version = "0.3"

features = [
    "console",
    "Document",
    "DocumentFragment",
    "Event",
    "HtmlElement",
    "HtmlHeadElement",
    "Location",
    "ShadowRoot",
    "ShadowRootInit",
    "ShadowRootMode",
    "Url",
    "Window",

    "Headers",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Blob",
]          

[dev-dependencies]
wasm-bindgen-test = "0.3"

[lib]
# crate-type = ["cdylib"]
crate-type = ["lib"]
